### ISSUE TITLE
Getting a ton of error messages

### ISSUE THREAD

**Issue by Gogo1951** [Ermad/angry-assignments#3]
Any idea how to fix this or, how I can help diagnose it? I had hundreds of these entries in my taint log last night. Is this a conflict with Elv?

8/17 20:17:29.740  An action was blocked in combat because of taint from AngryAssignments - SecureStateDriverManager:SetAttribute()
8/17 20:17:29.740      Interface\FrameXML\SecureStateDriver.lua:10
8/17 20:17:29.740      Interface\AddOns\ElvUI\Modules\UnitFrames\UnitFrames.lua:1017 CreateAndUpdateHeaderGroup()
8/17 20:17:29.740      Interface\AddOns\ElvUI\Modules\UnitFrames\UnitFrames.lua:1106 UpdateAllHeaders()
8/17 20:17:29.740      Interface\AddOns\ElvUI\Modules\UnitFrames\UnitFrames.lua:886 HandleSmartVisibility()
8/17 20:17:29.740      Interface\AddOns\ElvUI\Modules\UnitFrames\UnitFrames.lua:891 ?()
8/17 20:17:29.740      Interface\AddOns\AngryAssignments\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
8/17 20:17:29.740      xpcall()
8/17 20:17:29.740      Interface\AddOns\AngryAssignments\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29 Dispatch()
8/17 20:17:29.740      Interface\AddOns\AngryAssignments\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64 Fire()
8/17 20:17:29.740      Interface\AddOns\AngryAssignments\libs\AceEvent-3.0\AceEvent-3.0.lua:120
8/17 20:17:29.740  An action was blocked in combat because of taint from AngryAssignments - SecureStateDriverManager:SetAttribute()
8/17 20:17:29.740      Interface\FrameXML\SecureStateDriver.lua:11
8/17 20:17:29.740      Interface\AddOns\ElvUI\Modules\UnitFrames\UnitFrames.lua:1017 CreateAndUpdateHeaderGroup()
8/17 20:17:29.740      Interface\AddOns\ElvUI\Modules\UnitFrames\UnitFrames.lua:1106 UpdateAllHeaders()
8/17 20:17:29.740      Interface\AddOns\ElvUI\Modules\UnitFrames\UnitFrames.lua:886 HandleSmartVisibility()
8/17 20:17:29.740      Interface\AddOns\ElvUI\Modules\UnitFrames\UnitFrames.lua:891 ?()
8/17 20:17:29.740      Interface\AddOns\AngryAssignments\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
8/17 20:17:29.740      xpcall()
8/17 20:17:29.740      Interface\AddOns\AngryAssignments\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29 Dispatch()
8/17 20:17:29.740      Interface\AddOns\AngryAssignments\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64 Fire()

**Comment by Ermad** [comment]
Taint error message notoriously extremely frequently blame the wrong addon, especially when they use shared libraries like Ace. Need more info that its caused by Angry Assignments.

**Comment by Gogo1951** [comment]
Happy to provide more info, but it only started happening when I installed AngryAssignments. 

I work on addons as well. Best way to drive people away from an open source project is to close their issues before looking into them.
