### ISSUE TITLE
Please consider hosting somewhere else/in addition to Curse

### ISSUE THREAD

**Issue by Poisonenvy2** [Ermad/angry-assignments#4]
Noticed you'd hosted another addon of yours on Wago - wondered if you would mind hosting this one there too, please?  Casual raiding guild and this addon is brilliant - not only to aid my memory, but also to help other raid members.

**Comment by himea-saito** [comment]
Seconded: Please add to wowup!

**Comment by Dessyreqt** [comment]
All you need to do is turn your tags into releases and it will be supported by wowup by adding the repo.

**Comment by Ermad** [comment]
I have added it to Wago Addons

https://addons.wago.io/addons/angry-assignments
