### ISSUE TITLE
Error 10.0.0 Retail

### ISSUE THREAD

**Issue by Mithras2801** [Ermad/angry-assignments#5]
Message: Interface/AddOns/AngryAssignments/Core.lua:1615: attempt to call method 'SetMinResize' (a nil value)
Time: Mon Oct 31 05:56:08 2022
Count: 1
Stack: Interface/AddOns/AngryAssignments/Core.lua:1615: attempt to call method 'SetMinResize' (a nil value)

Locals: <none>

**Comment by mjheick** [comment]
Changes to make functional:

https://github.com/Ermad/angry-assignments/blob/master/Core.lua#L2097
- Change from "NONE" to ""

https://github.com/Ermad/angry-assignments/blob/master/Core.lua#L875
- Clear this line

https://github.com/Ermad/angry-assignments/blob/master/Core.lua#L1615-L1616
- Clear these lines

https://github.com/Ermad/angry-assignments/blob/master/AngryTreeGroup.lua#L571
- Clear this line

https://github.com/Ermad/angry-assignments/blob/master/AngryTreeGroup.lua#L650-L651
- Clear these lines

Et voilà

**Comment by Ermad** [comment]
Fixed in v1.15.0
